### ISSUE TITLE
Error building DOS32 on DosBox

### ISSUE THREAD

**Issue by viti95** [yetmorecode/dos32a-ng#2]
I've tried to build the project following the instructions, but fails building dos32.asm. This is the error:

![Captura de pantalla_2022-11-29_00-37-41](https://user-images.githubusercontent.com/8323882/204403545-c307c06f-de33-445b-b34b-b711ff024c53.png)

**Comment by viti95** [comment]
Found the culprit, the commit bf28a9419531b49119589d8ce3e595708a001616 doesn't compile correctly.

**Comment by yetmorecode** [comment]
Should work again. Apparently tasm does not recognize two symbols at the same address (apply_fixups and @@0 are the same).
