### ISSUE TITLE
-

### ISSUE THREAD

**Issue by necros2k7** [yetmorecode/dos32a-ng#3]
-

**Comment by leecher1337** [comment]
This is DOS code, not Windows

**Comment by necros2k7** [comment]
-

**Comment by yetmorecode** [comment]
Like this https://github.com/yetmorecode/dos32a-ng/releases/tag/9.1.2 ?

**Comment by necros2k7** [comment]
-

**Comment by yetmorecode** [comment]
> @yetmorecode Yes, thanx! And what`s the main benefit over classic version?

There is little to none. It's rather educational. The old D32A website was offline one day, no source control, build instructions not very clear, old tasm toolchain, etc.
